### ISSUE TITLE
伪元素详解

### ISSUE THREAD

**Issue by FavoriteJS** [FavoriteJS/myBlog#4]
## 伪元素
简介：伪元素有6个
::after,::before,::letter,::selection,::backdrop
常用的是::after和::before
一般来说伪元素使用(::)语法，而不是(:)
为了兼容IE8，保险的是使用单冒号
### 获取伪元素的属性值：
```javascript
	let before = window.getComputedStyle(myIdElement, ":before")
	before.width 直接使用键值访问
	before.getPropertyValue('width')
```
#### 区别：

+ 对于float属性，使用键值访问，不能使用getComputedStyle(ele, null).float,应该使用cssFloat与styleFloat
+ 之间使用键值访问，需要使用驼峰写法
+ getPropertyValue不支持驼峰写法
+ getPropertyValue()方法在IE9+和其他浏览器中可以实现，在IE6-8中使用getAttrbute()方法代替

> 伪元素的默认为行内元素，及"display:inline".如果没有定义display属性，及时在css设定"width:100px",最后获取的width值仍是auto

### 修改伪元素样式
1. 使用CSSStyleSheet的insertRule来为伪元素修改样式
例：

```javascript
	document.styleSheets[0].addRule('.red::before', 'color:green')
```
2. 修改伪元素的content的属性值

```javascript
	// 使用insertRule修改
	let latestContent = "修改过的内容";
	let formerContent = window.getComputedStyle($('.red'),'::before').getPropertyValue('content');
    document.styleSheets[0].addRule('.red::before','content: "' + latestContent + '"');
	document.styleSheets[0].insertRule('.red::before { content: "' + latestContent + '" }', 0);
	
	// 使用DOM元素的data-*属性修改
	//css
	.red::before{
		content: attr(data-attr);
	}
	//html
	<div class="red" data-attr="red"><div>
	//js
	document.querySelector('.red').setAttribute('data-attr', 'green')
	
```
### 注意点
> 1. 伪元素的content可以字符串和部分多媒体文件，但是content只存在源css的渲染
> 树种，并不存在真实的DOM中，所以为了SEO优化，最好不要再伪元素中包含与文档相
> 关的内容
> 2. 修改伪元素的样式建议通过更换class来修改样式。其他方法需要在js中插入字符代码，不利于与样式分离容易出错
> 3. 修改content属性的,推荐使用DOM的data-*属性来修改

利用class修改伪元素样式代码示例
css代码

```css
div.qtip{
    display: block;
    position: absolute;
    max-width: 300px;
    max-height: 200px;
    z-index: 2147483647;
    color: rgb(255, 255, 255);
    font-size: 11px;
    font-family: "Lucida Grande", sans-serif;
    font-weight: 700;
    line-height: 16px;
    text-shadow: rgb(0, 0, 0) 0px 1px;
    background: rgba(0, 0, 0, 0.87);
    border-width: 0px;
    border-style: solid;
    border-color: transparent;
    border-image: initial;
    padding:5px;
    border-radius: 4px;
    word-wrap: break-word; 
    word-break: normal; 
}
div.qtip:before{
    border-width: 0px 8px 8px;
    content: "";
    width: 0px;
    height: 0px;
    position: absolute;
    border-style: solid;
    border-width: 6px 6px 6px;
}
div.qtip_top:before{
    border-color: rgba(0, 0, 0, 0.87) transparent transparent transparent;
    top: 100%;
    right: calc(50% - 6px);
}
div.qtip_bottom:before{
    border-color: transparent transparent rgba(0, 0, 0, 0.87) transparent;
    bottom: 100%;
    right: calc(50% - 6px);
}
div.qtip_left:before{
    border-color: transparent transparent transparent rgba(0, 0, 0, 0.87);
    left:100%;
    bottom:calc(50% - 6px)
}
div.qtip_right:before{
    border-color: transparent rgba(0, 0, 0, 0.87) transparent transparent;
    right:100%;
    bottom:calc(50% - 6px)
}
```

html代码

```html
<div id="qtip">进入触发提示框<div>
```

js代码

```js
class Qtip {
	constructor() {
		$(document.body).append('<div class="nb_qtip"></div>')
		this.ele = $('div.qtip')
	}
	register(target, content, direc, flag) {
		let self = this
		target.on('mouseenter', function(e) {
			target = $(e.target)
			if(flag) content = target.text();
			console.log(content)
			if(!content) return
			self.removeClassName()
			self.ele.html(content)
			let l = target.offset().left,
				t = target.offset().top,
				gap = 20
			if (direc == 'x') {
				self.ele.css('top', t + target.height() / 2 - self.ele.outerHeight(true) / 2 + 'px')
					// let beforeStyle = window.getComputedStyle(self.ele.get(0), ':before')
				if (window.innerWidth > 2 * (l - document.body.scrollLeft)) {
					self.ele.addClass('nb_qtip_right')
					self.ele.css('left', l + target.width() + 6 + gap + 'px')
				} else {
					self.ele.addClass('nb_qtip_left')
					self.ele.css('left', l - self.ele.outerWidth(true) - 6 - gap + 'px')
				}
			} else {
				self.ele.css('left', l + target.width() / 2 - self.ele.width() / 2 + 'px')
				if (window.innerHeight > 2 * (t - document.body.scrollTop)) {
					self.ele.addClass('nb_qtip_bottom')
					self.ele.css('top', t + target.height() + 6 + gap + 'px')
				} else {
					self.ele.addClass('nb_qtip_top')
					self.ele.css('top', t - self.ele.outerHeight(true) - 6 - gap + 'px')
				}
			}
			self.ele.css('display', 'block')
		})
		target.on('mouseleave', function(e) {
			self.ele.css('display', 'none')
		})
	}
	removeClassName() {
		this.ele.removeClass('nb_qtip_top').removeClass('nb_qtip_bottom').removeClass('nb_qtip_right').removeClass('nb_qtip_left')
		this.ele.css('left', '').css('right', '').css('top', '').css('bottom', '')
	}
	destroy(target) {
		target.unbind('mouseenter mouseleave')
	}
}

let qitp = new Qtip()
qtip.register($('#qtip'), '请输入提示内容'， 'x', true) // 第三个参数为提示框显示的轴方向， 第四个参数为是否显示元素文本内容
```
